
trigger:
- main

stages:
- stage: Build 
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      buildConfiguration: 'Release'

    steps:
    - task: UseDotNet@2
      inputs:
        version: '5.0.x'
        includePreviewVersions: true # Required for preview versions
    - task: UseDotNet@2
      inputs:
        version: '3.1.x'
        packageType: runtime

    - task: DotNetCoreCLI@2
      displayName: 'Build project'
      inputs:
        projects: '**/*.csproj'
        arguments: '--output publish_output --configuration Release'
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
         rootFolderOrFile: 'publish_output/'
         includeRootFolder: false
         
    - task: AzureFunctionApp@1
      displayName: 'Deploy Azure Function App'
      inputs:
         azureSubscription: 'MAIC - Wicresoft - Azure - 09 (7bfee15b-b0d8-489b-89d7-604bbd66603a)'
         appType: 'functionAppLinux'
         appName: 'net5test2021-04'
         package: '$(Build.StagingDirectory)/*.zip'

