# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: Build 

  jobs:
  - job: Build

    pool:
      vmImage: 'ubuntu-latest'

    variables:
      buildConfiguration: 'Release'

    steps:
    - task: UseDotNet@2
      displayName: ".NET Core 3.1.x (needed for Azure Functions)"
      inputs:
        packageType: 'sdk'
        version: '3.1.x'
    - task: UseDotNet@2 
      displayName: ".NET Core 5.0.x (needed for everything else)"
      inputs:
        #version: '3.1.x'
        version: '5.0.x'
        packageType: sdk
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: "Publish"
      inputs:
        command: 'publish'
        projects: '**/net5test.csproj'
        publishWebProjects: false
        arguments: '-r linux-x64 --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/functions'
        zipAfterPublish: true
        modifyOutputPath: true

    - publish: '$(Build.ArtifactStagingDirectory)/functions' 
      artifact: functions_artifact

